// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/orders": {
            "get": {
                "description": "Show all order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Show all order",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/orderdelivery.GetAllOrderResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add new order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Add new order",
                "parameters": [
                    {
                        "description": "Create Order",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderdelivery.Orders"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/orders/{orderId}": {
            "put": {
                "description": "Update Order Data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Update Order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "orderId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Order",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/orderdelivery.UpdateOrder"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete order by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "delete order",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "orderId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "orderdelivery.GetAllOrderResponse": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/orderdelivery.Orders"
            }
        },
        "orderdelivery.Items": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Car"
                },
                "itemCode": {
                    "type": "string",
                    "example": "123"
                },
                "quantity": {
                    "type": "string",
                    "example": "2"
                }
            }
        },
        "orderdelivery.Orders": {
            "type": "object",
            "properties": {
                "customerName": {
                    "type": "string",
                    "example": "George"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/orderdelivery.Items"
                    }
                },
                "orderedAt": {
                    "type": "string",
                    "example": "2019-11-09T21:21:46Z"
                }
            }
        },
        "orderdelivery.UpdateItems": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Car"
                },
                "itemCode": {
                    "type": "string",
                    "example": "123"
                },
                "lineItemId": {
                    "type": "string",
                    "example": "12"
                },
                "quantity": {
                    "type": "string",
                    "example": "2"
                }
            }
        },
        "orderdelivery.UpdateOrder": {
            "type": "object",
            "properties": {
                "customerName": {
                    "type": "string",
                    "example": "George"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/orderdelivery.UpdateItems"
                    }
                },
                "orderedAt": {
                    "type": "string",
                    "example": "2019-11-09T21:21:46Z"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
